class Login_Locators:
    User_Name_Field = "//input[@name='username']"
    Password_Field = "//input[@type='password']"
    Login_Button = "//ion-button[contains(.,'Login')]"


class Patients_Locators:
    Patient_Tab = "//ion-tab-button[contains(.,'Patients')]"
    Patient_Reg_Icon = "//ion-button[@data-ion-popover-trigger='true']"
    New_Patient_Button = "//ion-text[@color='gray80'][contains(.,'New Patient')]"
    PGP_Dropdown_Arrow = "(//span[@class='k-button-icon k-icon k-i-caret-alt-down'])[9]"
    PGP_BOX = "(//input[@placeholder='*Physician Group'])[1]"
    FIRST_NAME_BOX = "//input[@placeholder='*First Name']"
    MIDDLE_NAME_BOX = "//input[@placeholder='Middle Name']"
    LAST_NAME_BOX = "//input[contains(@placeholder,'*Last Name')]"
    BIRTHDATE_FIELD = "//input[@id='datepicker-1']"
    GENDER_BOX = "//input[@placeholder='*Gender']"
    ADDRESS_FIELD = "//input[contains(@placeholder,'Address 1')]"
    ZIP_CODE_BOX = "//input[@placeholder='Zip']"
    MOBILE_NUMBER_FIELD = "(//input[contains(@type,'text')])[1]"
    HOME_NUMBER_FIELD = "(//input[contains(@type,'text')])[2]"
    EMAIL_BOX = "//input[contains(@placeholder,'Email')]"
    INSURANCE_ID_BOX = "//input[contains(@placeholder,'*ID')]"
    PHYSICIAN_DROPDOWN = "//input[@placeholder='*Physician']"
    Physician_Dropdown_Arrow = "//kendo-combobox[@placeholder='*Physician']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    Insurance_Dropdown_Arrow = "//kendo-combobox[@placeholder='*Primary Insurance']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    INSURANCE1_DROPDOWN = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[13]"
    SAVE_INITIATE_EPISODE_BUTTON = "//ion-text[contains(.,'Save & initiate Episode')]"
    Save_Patient_button = "//ion-text[contains(.,'save & close')]"
    Plus_Button_Office = "//div[@class='mb-5'][1]"
    Plus_Button_Fax = "//body/modal-container[1]/div[2]/div[1]/patient-registration[1]/div[1]/kendo-dialog[1]/div[2]/div[1]/div[1]/episodic-patient-registration[1]/div[1]/div[1]/ngx-simplebar[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[3]/div[2]/div[1]/div[3]/div[1]/div[2]/div[2]/ion-button[1]"
    Office_No_Option = "//ion-text[contains(.,'Office')]"
    Fax_Number_Option = "//ion-text[contains(.,'Fax')]"
    Office_Number_Box = "/html/body/modal-container/div[2]/div/patient-registration/div/kendo-dialog/div[2]/div/div/episodic-patient-registration/div/div/ngx-simplebar/div[1]/div[2]/div/div/div/div/form/div/div[3]/div[2]/div[1]/div[3]/div[1]/div[1]/kendo-formfield/div/kendo-maskedtextbox/input"
    Fax_No_Box = "/html/body/modal-container/div[2]/div/patient-registration/div/kendo-dialog/div[2]/div/div/episodic-patient-registration/div/div/ngx-simplebar/div[1]/div[2]/div/div/div/div/form/div/div[3]/div[2]/div[1]/div[4]/div/div[1]/kendo-formfield/div/kendo-maskedtextbox/input"
    Group_ID_Box = "//input[@placeholder=' Group ID']"
    Note_Box = "//textarea[@placeholder='Notes']"
    Exclude_Report_Box = "//input[@type='checkbox']"
    Pin_Icon = "(//ion-button[@fill='clear'])[5]"


class Episodes_Locators:
    Patient_Tab = "//ion-tab-button[contains(.,'Patients')]"
    Description_Box = "//input[@placeholder='Description (e.g. Right Knee Surgery)']"
    Physician_Box = "//input[@placeholder='*Physician']"
    Program_Dropdown = "//input[@placeholder='*Program']"
    Facility_Dropdown = "//input[@placeholder='*Facility']"
    PGP_Box = "/html/body/modal-container/div[2]/div/episode-add-new-episode-popup/div/kendo-dialog/div[2]/div/div/ion-list/form/div/div[1]/div[1]/kendo-formfield[1]/div"
    Facility_Dropdown_Arrow = "//kendo-combobox[@placeholder='*Facility']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    Facility_Box = "//input[@placeholder='*Facility']"
    Surgical_Facility = "//li[@role='option'][contains(.,'ACTIVE PHYSICAL THERAPY PLC')]"
    Dropdown_index = "(//li[@role='option'])[position()=1 or position()=2 or position()=3 or position()=4]"
    Surgery_Date = "//input[@id='datepicker-2']"
    Type = "//input[@placeholder='*Type']"
    Surgery_Type = "//label[@class='selectgroup-item']"
    Save_Button = "//ion-button[contains(.,'Save')]"
    Risk_Button = "//ion-text[contains(.,'Risk')]"
    Medium_Risk = "(//ion-text[contains(.,'Medium')])[1]"
    Target_Price = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/app-patients/div/div/div/patient-content/episodes-list/ngx-simplebar/div[1]/div[2]/div/div/div/div/div/section/div[2]/ion-card/div[2]/div[1]/div[2]/div[2]/div"
    Target_Price_Box = "//input[@role='spinbutton']"
    Episode_Notes = "(//ion-text[contains(.,'+ Note')])[1]"
    Episode_Note_Box = "//input[@placeholder='Add a note']"
    Add_Note_Tick = "//ion-button[@ng-reflect-disabled='false']"
    Care_Plan_Field = "//ion-text[contains(.,'+ Care Plan')]"
    Select_Index1_CarePlan = "//input[@id='tag0']"
    Next_Button = "//ion-button[contains(.,'Next')]"
    Save_Button_2 = "//ion-text[contains(.,'Save')]"
    Initiate_Buttton = "//ion-text[contains(.,'Initiate')]"


class Activities_Locators:
    Activities_Tab = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/main-nav/ion-tab-bar/ion-tab-button[3]/ion-label"
    Activities_Plus_Button = "//div[contains(@class, 'row-verticalCenter')]//ion-text[contains(text(), 'Activities')]/following-sibling::div[contains(@class, 'dropdown')]/ion-button[contains(@class, 'round-icon-button')]"
    Call_Activity_Option = "//li[normalize-space()='Call']"
    Category_Dropdown = "//input[@placeholder='Category*']"
    Category_Dropdown_Arrow = "//kendo-combobox[@id='category']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    Subject_Textbox = "//input[@placeholder='Subject*']"
    Assigned_To_Dropdown = "//input[@placeholder='Assigned To*']"
    Follow_up_Date_Dropdown = "//kendo-datepicker[@formcontrolname='exeStart']"
    Phone_Number = "//kendo-maskedtextbox[@formcontrolname='phone']"
    Save_Button = "//ion-button[contains(.,'Save')]"
    Form_Option = "//li[contains(.,'Form')]"
    Form_Box = "//input[@placeholder='Form*']"
    Form_Subject_Box = "//input[@placeholder='Subject*']"
    Save_Button_Form = "//ion-button[contains(.,'Save')]"


class Order_Locators:
    Orders_Tab = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/main-nav/ion-tab-bar/ion-tab-button[5]/ion-label"
    Filter_icon = "//ion-icon[@class='mr-10 header2 md ion-color ion-color-gray80 hydrated']"
    Facility_Dropdown = "//input[contains(@placeholder,'*Facility')]"
    Facility_Dropdown_Arrow = "(//span[@ng-reflect-ng-class='k-i-caret-alt-down'])[10]"
    Episodes_Tab = "//ion-label[@color='gray100'][contains(.,'Episodes')]"
    Search_Episode_Box = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/app-patients/div/episode-drawer/div/ion-list/div[1]/div[2]/kendo-combobox/kendo-searchbar/input"
    Searched_Episode_Index = "/html/body/app-root/ion-app/ion-router-outlet/app-main/div/app-patients/div/episode-drawer/div/ion-list/div[2]/ngx-simplebar/div[1]/div[2]/div/div/div/div/div[1]/div/div[3]/div/div/ion-text"
    Episode_Status_Filter = "//span[@class='k-input-value-text'][contains(.,'All')]"
    Status_Filter = "//span[@unselectable='on'][contains(.,'All')]"
    Planed_Filter = "//span[contains(.,'Planned')]"
    Apply_Button = "//ion-text[@class='body2-txt pl-30 md hydrated'][contains(.,'Apply')]"
    Episode_List_index1 = "(//div[@class='px-20 py-10 selectedList pointer'])[1]"
    Plus_Button_Order = "//div[contains(@class, 'row-verticalCenter')]//ion-text[contains(text(), 'Orders')]/following-sibling::div[contains(@class, 'dropdown')]/ion-button[contains(@class, 'round-icon-button')]"
    Home_Health_Tab = "//ul[@id='order-dropdown-menu']//li[@class='dropdown-item'][normalize-space()='Home Health']"  # Corrected capitalization of 'Home_Health_Tab'
    Description_Box = "//input[@placeholder='*Description']"
    Range_Field = "/html/body/modal-container/div[2]/div/app-episode-orders-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[3]/div[2]/div[1]/div/div[1]/kendo-textbox/input"
    Weeks_Field = "/html/body/modal-container/div[2]/div/app-episode-orders-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[3]/div[2]/div[1]/div/div[3]/kendo-textbox/input"
    Add_range_buttton = "//ion-icon[contains(@class,'icon-size pointer md ion-color ion-color-highlight hydrated')]"
    Save_Order_Button = "//ion-button[contains(.,'Save')]"
    Fees_Field = "/html/body/modal-container/div[2]/div/app-episode-orders-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[4]/div[1]/div/div[1]/kendo-textbox/input"
    Total_Amount = "(//input[@class='k-input-inner'])[10]"
    PT_Options = "//*[@id='order-dropdown-menu']/li[3]"
    SNF_Option = "//*[@id='order-dropdown-menu']/li[1]"
    SNF_Fees_Field = "/html/body/modal-container/div[2]/div/app-episode-orders-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[3]/div/div/div[1]/kendo-textbox/input"
    Days_Field_SNF = "/html/body/modal-container/div[2]/div/app-episode-orders-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[3]/div/div/div[2]/kendo-textbox/input"


class Notes_Locators:
    Notes_Plus_Button = "//div[contains(@class, 'row-verticalCenter')]//ion-text[contains(text(), 'Notes')]/following-sibling::div[contains(@class, 'dropdown')]/ion-button[contains(@class, 'round-icon-button')]"
    Notes_Category_Dropdown = "//input[@placeholder='*Category']"
    Enter_Note_Box = "//div[@data-placeholder='Enter note here...']"
    Save_Button = "//ion-text[contains(.,'Save')]"
    Important_Mark = "//ion-icon[@class='mb-7 ml-3 md hydrated']"
    Notes_Card_Index_1 = "(//ion-text[contains(.,'Tejas Nimbalkar')])[60]"
    Date_On_Right_Panel = "//span[@class='date']/text()"


class Utilization_Locators:
    Facility_Dropdown = "//input[@placeholder='*Facility']"
    Plus_Button_Utilization = "//ion-button[contains(@ng-reflect-disabled,'false')]"
    Inpatient_Utilization = "//li[contains(.,'Inpatient')]"
    Outpatient_Utilization = "//li[contains(.,'Outpatient')]"
    SNF_Utilization = "(//li[contains(.,'Skilled Nursing')])[1]"
    Home_Health_Utilization = "(//li[contains(.,'Home Health')])[1]"
    Provider_Dropdown_Arrow = "//kendo-combobox[@placeholder='*Provider']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    Facility_Dropdown_Arrow = "//kendo-combobox[@id='facility']//span[@class='k-button-icon k-icon k-i-caret-alt-down']"
    Provider_Dropdown = "//input[@placeholder='*Provider']"
    Estimated_Amount = "/html/body/modal-container/div[2]/div/app-episode-utilization-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[4]/kendo-formfield/div/kendo-numerictextbox/input"
    Save_Button = "//ion-button[contains(.,'Save')]"
    Estimated_Amount_Outpatient = "/html/body/modal-container/div[2]/div/app-episode-utilization-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[5]/kendo-formfield/div/kendo-numerictextbox/input"
    Estimated_Amount_SNF = "/html/body/modal-container/div[2]/div/app-episode-utilization-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[5]/kendo-formfield/div/kendo-numerictextbox/input"
    Estimated_Amount_HHA = "/html/body/modal-container/div[2]/div/app-episode-utilization-add-popup/kendo-dialog/div[2]/div/div/ion-list/form/div[5]/kendo-formfield/div/kendo-numerictextbox/input"


class Episodes_Worksheet_Locators:
    Episodes_Tab = "//ion-label[@color='gray100'][contains(.,'Episodes')]"
    Worksheet_Button = "//ion-icon[@title='My Episode Worklist']"
    Filter_button = "//ion-button[@title='Apply Filter']"


class Orders_Worksheet_Locators:
    Orders_Tab = "//ion-tab-button[contains(.,'Orders')]"
    Worksheet_Button = "//ion-icon[@title='My Orders Worklist']"
    Filter_button = "//button[contains(@title,'Apply Filter')]"
    Facility_text_Box = "//input[@placeholder='All Facility']"
    Provider_Textbox = "//input[@placeholder='All Provider']"
    Checked_In_Date = "//input[@placeholder='All Checked-in User']"
    Apply_Button = "//ion-text[@class='body2-txt md hydrated'][contains(.,'Apply')]"
    Reset_Button = "//ion-text[contains(.,'Reset')]"
    Checked_In_User_Box = "//input[@placeholder='All Checked-in User']"
    PGP_BOX = "//input[@placeholder='All PGP']"
